### ISSUE TITLE
helm lint : invalid Yaml document separator: apiVersion

### ISSUE THREAD

**Issue by matthias4217** [vidispine/hull#186]
I've encountered an error when linting my charts : `[ERROR] templates/hull.yaml: unable to parse YAML: invalid Yaml document separator: apiVersion: v1`

This happens with helm 3.7+. Helm 3.5 and 3.6 are fine and do not show such an error. Now, generating the template with `helm template` gives correct results, so this might be a helm issue.

---

A non-hull helm chart with this basic template succesfullt passes the lint. This is a similar output to `helm template` with the hull chart. :

`templates/test.yaml` (there is nothing else in the templates folder) :
```yaml
apiVersion: v1
data:
  testdata: lorem-ipsum
kind: ConfigMap
metadata:
  name: release-name-test-testconfigmap1
---
apiVersion: v1
data:
  testdata: dolor sic amet
kind: ConfigMap
metadata:
  name: release-name-test-testconfigmap2
```

---

However, such a Hull chart fails :

`values.yaml` :
```yaml
hull:
  objects:
    configmap:
      testConfigMap:
        data:
          testdata:
            inline: "lorem ipsum dolor"
```
`templates/hull.yaml` (there is nothing else in the templates folder) :
```
{{- include "hull.objects.prepare.all" (dict "HULL_ROOT_KEY" "hull" "ROOT_CONTEXT" $) }}
```

I don't really understand the cause, and if hull is at fault, or helm itself. I will continue investigating this.
