### ISSUE TITLE
Using transformations in objects' names

### ISSUE THREAD

**Issue by khmarochos** [vidispine/hull#264]
Hello!

First of all, thank you for sharing your work. The whole idea of generating Helm charts on the fly according to a single values file is fantastic.

I'm trying to use HULL in my work, and I'd like to ask you for some advice.

Is it possible to assign an object's name by a variable set by a user? Something kind of that:
```
hull:
  objects:
    secret:
      _HT^something.secretName:
<...skipped...>
something:
  secretName: my-secret
```
The user sets `something.secretName`, and my chart creates a Secret with this name prefixed by the chart and release names.

Obviously, the straightforward way I showed in my example won't work. So is there a right way to achieve this?

Thanks in advance for any hints.

P.S. Merry Christmas! 🎄
