### ISSUE TITLE
Something is wrong when using a transformation in hull.objects.ingress.*.tls.*.hosts

### ISSUE THREAD

**Issue by khmarochos** [vidispine/hull#272]
Hello again,

It seems that I've found another interesting phenomenon.

Let's assume we have the following `values.yaml`:
```
hull:
  objects:
    ingress:
      test:
        rules:
          default:
            host: example.org
            http:
              paths:
                root:
                  path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: test
                      port:
                        name: http
        tls:
          default:
            hosts:
              - example.org
            secretName: tls-certificate
```

Everything seems to be fine in this case, we get the following Ingress object:
```
kind: Ingress
metadata:
  annotations: {}
  labels:
    app.kubernetes.io/component: test
    app.kubernetes.io/instance: test
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: hull-test-3
    app.kubernetes.io/part-of: undefined
    app.kubernetes.io/version: 0.0.0
    helm.sh/chart: hull-test-3-0.0.0
  name: test-hull-test-3-test
  namespace: default
spec:
  rules:
  - host: example.org
    http:
      paths:
      - backend:
          service:
            name: test-hull-test-3-test
            port:
              name: http
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - example.org
    secretName: test-hull-test-3-tls-certificate
```

The `spec.tls` part is valid.

But when we try to use a transformation in `hull.objects.ingress.*.tls.*.hosts`, we have something different.

Here's `values.yaml`:
```
hull:
  objects:
    ingress:
      test:
        rules:
          default:
            host: example.org
            http:
              paths:
                root:
                  path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: test
                      port:
                        name: http
        tls:
          default:
            hosts:
              - _HT/util.domainNames.getIngressHostname
            secretName: tls-certificate
```

The `templates/_domain_names.tpl` module is simple and straightforward:
```
{{- define "util.domainNames.getIngressHostname" -}}
example.org
{{- end -}}
```

In this case we have the following result:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations: {}
  labels:
    app.kubernetes.io/component: test
    app.kubernetes.io/instance: test
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: hull-test-3
    app.kubernetes.io/part-of: undefined
    app.kubernetes.io/version: 0.0.0
    helm.sh/chart: hull-test-3-0.0.0
  name: test-hull-test-3-test
  namespace: default
spec:
  rules:
  - host: example.org
    http:
      paths:
      - backend:
          service:
            name: test-hull-test-3-test
            port:
              name: http
        path: /
        pathType: Prefix
  tls:
  - hosts: example.org
    secretName: test-hull-test-3-tls-certificate
```

The `spec.tls` structure is wrong: the `hosts` parameter has become a string instead of being an array.

What do you think, why does it happen?

Thank you!

**Comment by khmarochos** [comment]
I changed `_HT/util.domainNames.getIngressHostname` to `_HT/hosts/util.domainNames.getIngressHostname` in `values.yaml`:
```
hull:
  objects:
    ingress:
      test:
        rules:
          default:
            host: example.org
            http:
              paths:
                root:
                  path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: test
                      port:
                        name: http
        tls:
          default:
            hosts: _HT/hosts/util.domainNames.getIngressHostname
            secretName: tls-certificate
```

`templates/_domain_names.tpl`:
```
{{- define "util.domainNames.getIngressHostname" -}}
hosts:
- example.org
{{- end -}}
```

The result:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations: {}
  labels:
    app.kubernetes.io/component: test
    app.kubernetes.io/instance: test
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: hull-test-3
    app.kubernetes.io/part-of: undefined
    app.kubernetes.io/version: 0.0.0
    helm.sh/chart: hull-test-3-0.0.0
  name: test-hull-test-3-test
  namespace: kloudster-control-plane
spec:
  rules:
  - host: example.org
    http:
      paths:
      - backend:
          service:
            name: test-hull-test-3-test
            port:
              name: http
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - example.org
    secretName: test-hull-test-3-tls-certificate
```

But why does it work this way (when I use a transformation for the whole `spec.tls.hosts`) and doesn't work that way (when I use a transformation for one element of `spec.tls.hosts` only)?
