### ISSUE TITLE
hull.util.transformation.get converts a string to an integer

### ISSUE THREAD

**Issue by khmarochos** [vidispine/hull#276]
Hello!

It seems that I've found an unexpected (at least by me) scenario when a string is being forcefully converted to an integer by `hull.util.transformation.get`.

Here's a minimalistic values set:
```yaml
hull:
  objects:
    job:
      my-job:
        pod:
          containers:
            my-container:
              image:
                registry: my-registry.local
                repository: my-repository
                tag: _HT*image.tag
image:
  tag: "09956e29" # in my "real-world" case this value is just a commit tag, the `image.tag` value is set by the CI pipeline
```

And here's what I get in `spec.template.spec.containers[0].image`:
```
my-registry.local/my-repository:9.956e+32
```

Can I prevent this behaviour?

Thank you in advance, I'm really sorry for disturbance.
