### ISSUE TITLE
Accessing the global context from an interpolation placeholder

### ISSUE THREAD

**Issue by khmarochos** [vidispine/hull#288]
Hello again!

I hope, it's perfect time for another stupid question. :-)

Would you be so kind as to help me to understand how to access the "global context" from an interpolation placeholder? Here's what I mean:
```yaml
hull:
  objects:
    configmap:
      my-configmap:
        data:
          my-parameter-1:
            inline: _HT!{{ printf "Hello, world! My name is %s." (index . "$").Values.myName }}
          my-parameter-2:
            inline: Hello, world! My name is {{ (index . "$").Values.myName }}.
myName: Some Name
```

The `my-parameter-1` is being rendered correctly, but I can't figure out how to make `my-parameter-2` being rendered too.

Could you help me to comprehend it, please?

**Comment by khmarochos** [comment]
...of course, I can just create a template in the `templates` subdirectory and it would work fine:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap-is-okay
data:
  my-parameter: Hello, world! My name is {{ .Values.myName }}.
```

But I'd really like to keep some objects' definitions in the main values set.

**Comment by khmarochos** [comment]
...of course, I tried to examine the dump of `$` (`helm install --dry-run test . --set hull.objects.configmap.my-configmap.data.dump.inline='\{\{ toYaml $ \}\}' --set someParameterIsSet=true`), but it seems that there are no references. It would be so nice to be able to reach the parent context with something like `index . "PARENT_CONTEXT"` from inside of the placeholder! :-)

**Comment by khmarochos** [comment]
I've found a funny workaround, will implement it in my charts :-)

```yaml
hull:
  config:
    myName: _HT!{{ (index . "$").Values.myName }}
  objects:
    configmap:
      my-configmap:
        data:
          my-parameter:
            inline: Hello, world! My name is {{ $.Values.hull.config.myName }}.
myName: Some Name
```

**Comment by khmarochos** [comment]
And even a bit better one:
```yaml
hull:
  GLOBAL_CONTEXT: _HT!{{ (index . "$") | toJson }}
  objects:
    configmap:
      my-configmap:
        data:
          my-parameter:
            inline: Hello, world! My name is {{ $.Values.hull.GLOBAL_CONTEXT.Values.myName }}.
myName: Some Name
```

**Comment by gre9ory** [comment]
Hi @khmarochos, hope you are doing ok!

Before usual attempt at explanations, I first want to mention that there maybe two pretty advanced usages of HULL that I haven't tested or used much myself: 

1. Subchart one HULL chart in another HULL chart (certainly some Docker-in-Docker vibes here). I have never tested this excessively but a colleague of mine has built a fairly complex chart like this and it worked as expected so far and he got everything done. So I think this scenario can be considered supported.

2. Adding HULL charts to a chart with other "handmade" configurations outside of `hull:` scope. This could be due to extra "regular" templates in your charts or other subcharts being included. This  "cross-access" from HULL to other root values in `$` scope is what you are doing here, which is very interesting but honestly not been in my scope much yet. I created a lot of pure hull charts (no extra templates or subcharts) which always sufficed for me. In my view, the HULL side of things primarily needs to work in a self contained way - but of course extending scope is always worth exploring.

That aside, the first thing about your example is that in `my-parameter-2` you don't have to (and actially can't) use the `(index . "$")` to access the global context `$`. As I tried to explain in the other issue [here](https://github.com/vidispine/hull/issues/267), within `values.yaml` you can use `.` and `$` in the ConfigMap and Secret `data` which comes from the `inline` and `path` fields directly. This is because `tpl` is always run on the content of these fields, making the use of `_HT!` obsolete here and only here. Everywhere else you must use `_HT!` for templating access and then you must also use `(index . "$").Values` instead of `$.Values`. Technically this is due to the original chart context `$` being passed as a parameter `"$"` to `_HT!` in the argument dict.

I'll try to put it into memorable notes:

> When doing `tpl` templating in the `values.yaml`, use `_HT!` as a prefix and access parent chart values with `(index . "$").Values`. 

> This also applies to `configmap` and `secret`'s `inline` content or within files referenced via `path`.

> However, for these two fields contents you can also leave out `_HT!` and can directly use `$.Values` when templating. 

> But don't mix styles here! Use either `_HT!` prefix and `(index . "$").Values` or leave out `_HT!` and use `$.Values`

But the fun fact is even if you correct this then to:
 ```
 hull:
  objects:
    configmap:
      my-configmap:
        data:
          my-parameter-2:
            inline: Hello, world! My name is {{ $.Values.myName }}
myName: Some Name
``` 
 it comes out as `Hello, world! My name is `. It does not fill in the correct value as it theoretically should. Even with the corrected access to the context, the `_HT!` in `my-parameter-1` does provide the access to `Values.myName` but the `.Values.myName` in `my-parameter-2` does not.
 
This unexpected behavior should not exist and after some researching into the code I found out why it does. I'll try to explain:

Basically the whole processing kicks off in the `hull.yaml`, which is being executed in the parent charts `templates` folder. The parent Helm charts global context is being passed along from here to all functions executed down the line so that they may have access to the parent chart context. 

Quite early on in the whole processing,  the YAML is checked for HULL transformations and they are evaluated. At this stage the original parent charts context is available and being accessed. This is why the `my-parameter-1` has access to `Values.myName` and does render out fine. 
 
But I found that when passing the parent context to ConfigMaps and Secret rendering functions there was a problem. An by now obsolete piece of code changes the context being passed on to only contain the `.Values.hull` configuration values. All other keys from `.Values` were removed. This actually explains why it doesn't work in `my-parameter-2`, the `myName` in `.Values` basically got lost on the way. 

Since I did not care much yet for out of `.Values.hull` scope configuration values, I guess I did not realize that problem. After removing the problematic and by now stale code. the tests still are green __and__ you get access to other properties of `.Values` besides `hull` such as to your `myName` field.

Long story short again: will fix this so it works for you in a straight and expected way. Once fixed, the following will render for you as expected, giving you `Hello, world! My name is someName.` for both `my-parameter-1` and `my-parameter-2`:

```
hull:
  objects:
    configmap:
      my-configmap:
        data:
          my-parameter-1:
            inline: _HT!{{ printf "Hello, world! My name is %s." (index . "$").Values.myName }}
          my-parameter-2:
            inline: Hello, world! My name is {{ $.Values.myName }}.
myName: Some Name
```
 
Sorry for lengthy explanations, I like to do that to keep track of what happened for myself or others later. You might not think of it that way but your "simple" question resulted in a nice improvement (or bug fix) again so please keep on asking those questions.  When something does not work as expected it actually often points to a real underlying fault.

 Also really like your creativity with the workarounds 👍
 
 Expect some new releases the next couple of days to fix this. Thanks!

**Comment by gre9ory** [comment]
Wiith the new releases you can now use all of below possibilities to reference variables that exist outside of `.Values.hull`, irrelevant if it is Secret or ConfigMap content, `inline` or in a file via `path`:

```
myName: Some Name
subdict:
  myName: Some Other Name
hull:
  objects:
    configmap:
      non-hull-values-access:
        data:
          inline-issue-288-dollar:
            inline: Hello, world! My name is {{ $.Values.myName }}.
          inline-issue-288-dot:
            inline: Hello, world! My name is {{ .Values.myName }}.
          inline-issue-288-ht-get:
            inline: _HT*myName
          inline-issue-288-ht-tpl:
            inline: _HT!{{ printf "Hello, world! My name is %s." (index . "$").Values.myName }}
          inline-subdict-access-dollar:
            inline: "{{ $.Values.subdict.myName }}"
          inline-subdict-access-dot:
            inline: "{{ .Values.subdict.myName }}"
          inline-subdict-access-ht-get:
            inline: _HT*subdict.myName
          inline-subdict-access-ht-get-json:
            inline: _HT*toJson|subdict
          inline-subdict-access-ht-get-prettyjson:
            inline: _HT*toPrettyJson|subdict
          inline-subdict-access-ht-get-rawjson:
            inline: _HT*toRawJson|subdict
          inline-subdict-access-ht-get-string:
            inline: _HT*toString|subdict
          inline-subdict-access-ht-get-yaml:
            inline: _HT*toYaml|subdict
          inline-subdict-access-ht-tpl:
            inline: _HT!{{ (index . "$").Values.subdict.myName }}
```

yields a ConfigMap like this:

```
apiVersion: v1
data:
  inline-issue-288-dollar: Hello, world! My name is Some Name.
  inline-issue-288-dot: Hello, world! My name is Some Name.
  inline-issue-288-ht-get: Some Name
  inline-issue-288-ht-tpl: Hello, world! My name is Some Name.
  inline-subdict-access-dollar: Some Other Name
  inline-subdict-access-dot: Some Other Name
  inline-subdict-access-ht-get: Some Other Name
  inline-subdict-access-ht-get-json: '{"myName":"Some Other Name"}'
  inline-subdict-access-ht-get-prettyjson: |-
    {
      "myName": "Some Other Name"
    }
  inline-subdict-access-ht-get-rawjson: '{"myName":"Some Other Name"}'
  inline-subdict-access-ht-get-string: map[myName:Some Other Name]
  inline-subdict-access-ht-get-yaml: 'myName: Some Other Name'
  inline-subdict-access-ht-tpl: Some Other Name
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: non-hull-values-access
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: hull-test
    app.kubernetes.io/part-of: undefined
    app.kubernetes.io/version: 1.29.0
    helm.sh/chart: hull-test-1.29.0
  name: release-name-hull-test-non-hull-values-access
  namespace: default
```

As explained, outside of ConfigMaps and Secrets you can always (and only) use the `_HT` transformations and `(index . "$")` to access non-`hull` values from your `values.yaml`.

These are the releases with the bug fixes:

[1.27.12](https://github.com/vidispine/hull/releases/tag/hull-1.27.12)
[1.28.10](https://github.com/vidispine/hull/releases/tag/hull-1.28.10)
[1.29.4](https://github.com/vidispine/hull/releases/tag/hull-1.29.4)
