### ISSUE TITLE
What is the most ideomatic way of rendering inline JSON in CRD ?

### ISSUE THREAD

**Issue by eshepelyuk** [vidispine/hull#339]
Hello 

I have to render CRD looking smth like this

```yaml
.....
spec:
  forProvider:
    inlinePolicy:
      - name: default
        policy: |
          {
            "Version": "2012-10-17",
            "Statement": [
              {
                "Effect": "Allow",
                "Resource": "*",
                "Action": "ssm:GetParameter*"
              }
            ]
          }
```

Using naive `_HT!{{ .. }}` block, I am receiving YAML result and according to docs it's an expected behaviour.
So to render inline JSON - I've declared a new value in `hull.config.specific` and later used `_HT*toPrettyJson|hull.config.specific.inlineJson` to render it.

It works OK now, but I'd like to understand 
* is this recommended/ideomatic approach 
* is this syntax covered in docs, because I only discovered it by checking test cases

Thanks in advance.
