### ISSUE TITLE
K8s Gateway API bugs

### ISSUE THREAD

**Issue by eshepelyuk** [vidispine/hull#354]
Hello

This is a feedback to #345

### Port can not be configured from a Helm value.

Considering following `values.yaml`

```yaml
hull:
  config:
    specific:
      httpPort: 8080
  objects:
    service:
      default:
        type: ClusterIP
        ports:
          http:
            port: _HT*hull.config.specific.httpPort
            targetPort: http
    httproute:
      default:
        hostnames: [localhost]
        parentRefs:
          - group: gateway.networking.k8s.io
            kind: Gateway
            name: envoy-default
            namespace: envoy
            sectionName: https
        rules:
          - backendRefs:
              - name: _HT^default
                port: _HT*hull.config.specific.httpPort
            matches: []
```

Rendering helm chart results into following errors

```
Error: values don't meet the specifications of the schema(s) in the following chart(s):
hull:
- (root): Must validate at least one schema (anyOf)
- objects.httproute.default: Must validate at least one schema (anyOf)
- objects.httproute.default: Must validate "else" as "if" was not valid
- objects.httproute.default.rules.0.backendRefs.0: Must validate at least one schema (anyOf)
- objects.httproute.default.rules.0.backendRefs.0.port: Invalid type. Expected: integer, given: string
- objects.httproute.default.rules.0.backendRefs.0: Must validate all the schemas (allOf)
- objects.httproute.default.rules.0.backendRefs.0: Must validate all the schemas (allOf)
- objects.httproute.default.rules.0: Must validate all the schemas (allOf)
- objects.httproute.default: Must validate all the schemas (allOf)
```

Changing `port: _HT*hull.config.specific.httpPort` to `port: 8080` fixes the issues

**Comment by gre9ory** [comment]
Hi @eshepelyuk,

let me first reiterate some aspects about how HULL represents dedicated Kubernetes objects properties which are arrays as dictionaries on the HULL side. Think you are aware of this but maybe it helps resolving some expectation problems.

---

When implementing Gateway API, I tried to come up with an appropriate interface which in some places represents array properties as dictionary properties. This is to make it possible to explicitly override and manipulate specific entries from the collection of entries. As discussed a lot on this site, configuring arrays on the input side comes with severe problems in the Helm world and the closer to the root the array is in the object tree the worser the effect is. 

From your code, I can see you were sticking with array inputs for `parentRefs`, `rules` and `matches`. Actually, in other older object types I would not expect this to work. But as a "hidden" feature I experimented with alternatively allowing array input in the Gateway API objects which HULL normally represents as dictionaries.  

So my point here is that I would advise to use the dictionary input structure instead of the array structure here. It is from my point of view the only fully supported way of providing input to HULL and using arrays where HULL "favors" a dictionary is not guaranteed to be fully supported. 

I can understand that it may sometimes be a bit counter intuitive when you are expecting array structures, being familiar with the Kubernetes objects, but HULL utilizes dictionary structures. Generally, if you want to see which array fields are represented as dictionary fields, you can refer to the `values.yaml`. In all the object instance default structures, anytime there is a `_HULL_OBJECT_TYPE_DEFAULT_` in the tree starting from the third level this means this field is a dictionary on the HULL side. 

For example, in this `values.yaml` code the `tls` and `rules` fields on the third level are dictionaries and also `paths` is expecting a dictionary input:

```
# INGRESSES 
  ingress:
    _HULL_OBJECT_TYPE_DEFAULT_:
      enabled: true
      annotations: {}
      labels: {}
      tls:
        _HULL_OBJECT_TYPE_DEFAULT_: {}
      rules:
        _HULL_OBJECT_TYPE_DEFAULT_:
          http:
            paths:
              _HULL_OBJECT_TYPE_DEFAULT_: {}
```

On the practical note, my experience is that it improved overall configurability significantly to switch dedicated array fields to dictionary representations, especially if you stack many layers of `values.yaml`s in your configuration. Regarding Gateway API, since I am lacking practical experience with it's object types, I tried to come up with an interface that seemed reasonable for me when studying the documentation and schemas.

Here is the Gateway API structure in `values.yaml`:

 ```
# GATEWAY API - BACKENDLBPOLICY
  backendlbpolicy:
    _HULL_OBJECT_TYPE_DEFAULT_:
      enabled: true
      annotations: {}
      labels: {}
      targetRefs:
        _HULL_OBJECT_TYPE_DEFAULT_: {}
      
##################################################

# GATEWAY API - BACKENDTLSPOLICY
  backendtlspolicy:
    _HULL_OBJECT_TYPE_DEFAULT_:
      enabled: true
      annotations: {}
      labels: {}
      targetRefs:
        _HULL_OBJECT_TYPE_DEFAULT_: {}
##################################################

# GATEWAY API - GATEWAYCLASS
  gatewayclass:
    _HULL_OBJECT_TYPE_DEFAULT_:
      enabled: true
      annotations: {}
      labels: {}
##################################################

# GATEWAY API - GATEWAY
  gateway:
    _HULL_OBJECT_TYPE_DEFAULT_:
      enabled: true
      annotations: {}
      labels: {}
      addresses: 
        _HULL_OBJECT_TYPE_DEFAULT_: {}
      listeners:
        _HULL_OBJECT_TYPE_DEFAULT_: 
          tls:
            certificateRefs:
              _HULL_OBJECT_TYPE_DEFAULT_: {}
            frontendValidation:
              caCertificateRefs:
                _HULL_OBJECT_TYPE_DEFAULT_: {}
          allowedRoutes:
            kinds:
              _HULL_OBJECT_TYPE_DEFAULT_: {}
##################################################

# GATEWAY API - GRPCROUTE
  grpcroute:
    _HULL_OBJECT_TYPE_DEFAULT_:
      enabled: true
      annotations: {}
      labels: {}
      parentRefs: 
        _HULL_OBJECT_TYPE_DEFAULT_: {}
      rules:
        _HULL_OBJECT_TYPE_DEFAULT_: 
          matches:
            _HULL_OBJECT_TYPE_DEFAULT_: {}
          filters:
            _HULL_OBJECT_TYPE_DEFAULT_: {}
          backendRefs:
            _HULL_OBJECT_TYPE_DEFAULT_:
              filters:
                _HULL_OBJECT_TYPE_DEFAULT_: {}
##################################################

# GATEWAY API - REFERENCEGRANT
  referencegrant:
    _HULL_OBJECT_TYPE_DEFAULT_:
      enabled: true
      annotations: {}
      labels: {}
      from: 
        _HULL_OBJECT_TYPE_DEFAULT_: {}
      to:
        _HULL_OBJECT_TYPE_DEFAULT_: {}
##################################################

# GATEWAY API - TCPROUTE
  tcproute:
    _HULL_OBJECT_TYPE_DEFAULT_:
      enabled: true
      annotations: {}
      labels: {}
      parentRefs: 
        _HULL_OBJECT_TYPE_DEFAULT_: {}
      rules:
        _HULL_OBJECT_TYPE_DEFAULT_: 
          backendRefs:
            _HULL_OBJECT_TYPE_DEFAULT_: {}
##################################################

# GATEWAY API - TLSROUTE
  tlsroute:
    _HULL_OBJECT_TYPE_DEFAULT_:
      enabled: true
      annotations: {}
      labels: {}
      parentRefs: 
        _HULL_OBJECT_TYPE_DEFAULT_: {}
      rules:
        _HULL_OBJECT_TYPE_DEFAULT_: 
          backendRefs:
            _HULL_OBJECT_TYPE_DEFAULT_: {}
##################################################

# GATEWAY API - UDPROUTE
  udproute:
    _HULL_OBJECT_TYPE_DEFAULT_:
      enabled: true
      annotations: {}
      labels: {}
      parentRefs: 
        _HULL_OBJECT_TYPE_DEFAULT_: {}
      rules:
        _HULL_OBJECT_TYPE_DEFAULT_: 
          backendRefs:
            _HULL_OBJECT_TYPE_DEFAULT_: {}
##################################################

# GATEWAY API - HTTPROUTE
  httproute:
    _HULL_OBJECT_TYPE_DEFAULT_:
      enabled: true
      annotations: {}
      labels: {}
      parentRefs: 
        _HULL_OBJECT_TYPE_DEFAULT_: {}
      rules:
        _HULL_OBJECT_TYPE_DEFAULT_: 
          matches:
            _HULL_OBJECT_TYPE_DEFAULT_: {}
          filters:
            _HULL_OBJECT_TYPE_DEFAULT_: {}
          backendRefs:
            _HULL_OBJECT_TYPE_DEFAULT_:
              filters:
                _HULL_OBJECT_TYPE_DEFAULT_: {}
##################################################
```

---

About your actual problem, it lies in the `values.yaml.json` schema validation of the input and is not directly related to what I wrote above. I saw that there several fields misconfigured and don't allow the `_HT` HULL transformation syntax as input values. Will fix this and get back to you on that shortly.
