### ISSUE TITLE
[question] How to render property file in ConfigMap

### ISSUE THREAD

**Issue by eshepelyuk** [vidispine/hull#359]
Hello 

I am trying to create `ConfigMap` with properties file inside, using `values.yaml` like this:

```yaml
hull:
  objects:
    configmap:
      config:
        data:
          application.properties:
            inline: |
              _HT!
                my.prop1 = val1
                my.prop2 = {{ printf "val2" }}
```

but it renders without line breaks like below.

```yaml
apiVersion: v1
data:
  application.properties: my.prop1 = val1 my.prop2 = val2
kind: ConfigMap
```

what I expect 

```yaml
apiVersion: v1
data:
  application.properties: |
    my.prop1 = val1 
    my.prop2 = val2
kind: ConfigMap
```

How can I achieve this ?
Thnx n advance.
